# Generated by Django 5.1.7 on 2025-04-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_scheduleavailability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigators',
            options={'verbose_name': 'Navigators', 'verbose_name_plural': 'Navigators'},
        ),
        migrations.AlterModelOptions(
            name='scheduleavailability',
            options={'verbose_name': 'ScheduleAvailability', 'verbose_name_plural': 'ScheduleAvailabilities'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Students', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='students',
            name='token',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
